### ISSUE TITLE
서버와 DB에서 post expiredTime을 다루는 방법

### ISSUE THREAD

**Issue by JMKiim** [BedalFriend/BaedalFriend-FE#12]
## Description

> 서버와 DB에서 post expiredTime을 다루는 방법

방금 백엔드 쪽에 제안 드린 posts 저장 방식과 expiredTime 처리 방법입니다.

## Progress

```
데이터베이스
ㄴ users
   ㄴ 김재명
   ㄴ 백두산
   ㄴ 이호진
ㄴ posts
   ㄴ 서울
      ㄴ 1번글
         {
            id: 1,
            내용..
            작성자...
            createdAt: 2022-11-10@T13:01:30.1586,
            expiredTime: 7200,
            ....
         }
      ㄴ 3번글
   ㄴ 인천
      ㄴ 2번글
      ㄴ 4번글
   ㄴ 부산
      ㄴ 5번글
ㄴ comments
   ㄴ 1번 댓글
   ㄴ 2번 댓글
```

클라이언트에서 '서울' 모집 글 전체에 대한 get 요청을 함
그러면 서버에서 클라이언트로 1번 글과 3번 글을 담은 배열을 줘야 함!

그러면 서버에서 1번 글과 3번 글에 대해서 각각 해줘야 할 일은?
해당 글에 대해서 get 요청이 온 시각 2022-11-11@~~
이것을 해당 글 modifiedAt 값과 비교해서 시간 차 구하기 -> (초 단위) 2550 차이

클라이언트에 expiredTime 넘겨줄 때 7200-2550를 계산하고, 결국 주는 값은 4650 이어야 한다.
데이터베이스 1번 글의 expiredTime을 4650으로 수정해준다.

마무리 작업: 만약 expiredTime이 0 혹은 0보다 작아지는 글이 생긴다면 
                     해당 글의 isDone을 true로 바꿔준다.

**Comment by JMKiim** [comment]
```
{
	id: 1,
	작성자...
	createdAt: 2022-11-10@T13:01:30.1586,
	limitTime: '2022-11-10 17:30:25'
	...
	isDone: false,
}
```

[서버] get요청 들어옴 => 서버 코드 중에 get요청 받는 함수 -> 그 함수 내부에서 현재 시각을 불러오기
=== >get 요청이 들어온 시각  2022-11-10 17:35:59 ~~

해당 시각을 limitTime과 비교해보기 -> 
1. get요청이 들어온 시간이 limitTime에 미치지 못함 -> 그대로 response에 담아주기
2. get요청이 들어온 시간이 limitTime과 같거나 이미 지남 -> isDone을 true로 바꿔서 보내기


--FE TODO--
get요청한 이유가 마감임박인 게시글들 표시해주기 위함 이라면...
mapping 하면서 하나 씩 확인해서 isDone이 true인 글들 일단 제외,
isDone이 false인 게시글들 대상으로 아래의 계산 진행

new Date()를 통해 뽑아온 현재 시각(즉 클라이언트가 get 요청 한 시각) 과
게시글 객체 안에 들어있는 limitTime 날짜 정보를 차이 비교함.
limitTime - currentTime 했을때 값이 100분 = 6000 이내인 게시글들만 return해줌



추가 논의 후 변경 사항입니다.

**Comment by rohheejin** [comment]
@JMKiim 
변경 사항대로 처리가 된다면 보다 쉽게 구현할 수 있을 거 같습니다.
사용자의 입장에서도 게시글의 모임 마감시간이 사용자가 주문을 이행하는 시간으로 바뀐 게 좋다고 생각합니다.

**Comment by JMKiim** [comment]
limitTime을 활용하는것으로 확정되었고 해당 값의 양식은
'YYYY-MM-DD HH:mm:ss' 입니다.
