### ISSUE TITLE
[화면구현 제안] Upload 페이지

### ISSUE THREAD

**Issue by rohheejin** [BedalFriend/BaedalFriend-FE#22]
## Description
<img width="491" alt="image" src="https://user-images.githubusercontent.com/100185218/201525181-5caf589a-fd6c-4c3c-ac23-0b09e391e08d.png">

> 디자이너님과 Upload 페이지를 의논해본 결과 업로드를 두단계로 나눠서 진행할 예정입니다.
> 의견을 말씀해주시면 감사하겠습니다.

**Comment by JMKiim** [comment]
index라는 변수를 state로 관리하고
index가 0일때는 왼쪽 컴포넌트를 리턴해주고 index가 1일때는 오른쪽 컴포넌트를 리턴해주면 될것같습니다.
다음단계 이전단계 각각의 버튼을 클릭하면 set state로 index의 값을 변경해주면 리렌더링이 일어날겁니다.

**Comment by mingki831** [comment]
기입사항이 많으니 2단계로 나눠서 진행하는 방식 좋습니다!!
다만.. 카테고리 선택부분에서 다른 페이지로 넘어갔다가 와서 페이지가 3개가 되는 것 보다 더 간단한 방법으로 선택할 수 있으면 좋겠다는 개인적인 생각을 해보았습니다..!

**Comment by JMKiim** [comment]
어제 수정 된 게시글 하단 버튼만 적용하면 될 것 같습니다!
