### ISSUE TITLE
[사용법] useOutSideClick

### ISSUE THREAD

**Issue by mingki831** [BedalFriend/BaedalFriend-FE#26]
### hooks > useOutSideClick.js

검색 페이지 모달 부분을 구현하다가 모달 밖을 클릭했을 때 모달창이 닫히게 하는 부분을 위해 공통적으로 사용할 수 있는 hook을 추가해놓았습니다!

![](https://velog.velcdn.com/images/mingki831/post/0c9cb9cd-aca3-462a-bfdc-b05a07a8f0e7/image.png)

hook 내용은,
ref로 지정한 요소의 밖을 클릭했을 때 callback 함수를 실행시켜준다는 내용입니다.

![](https://velog.velcdn.com/images/mingki831/post/1b095e83-17fe-467d-b346-7d348a3d5d30/image.png)

제가 모달에 적용한 부분입니다.
먼저 hook을 import 해준 상태에서 useRef를 사용해 ModalWrap의 컨테이너 요소를 담아줍니다.
그리고 ModalWrap의 외부를 클릭했을 때 handleClose()가 실행되도록 설정해주었습니다.
handleClose()에는 모달창을 닫는 useState가 존재하는 페이지에서 모달창을 닫는 함수를 props로 받아와서 넣어주기만 하시면 됩니다. (제 경우 onClose)

확인해주시면 PR 올리겠습니다!

**Comment by JMKiim** [comment]
확인했습니다. 혹시 모달 애니메이션도 적용해보셨나요??

**Comment by mingki831** [comment]
@JMKiim 아니요 애니메이션은 넣지 않았습니다 기본 fade-in, fade-out 넣어볼까요?

**Comment by mingki831** [comment]
@mingki831 추가해놓았습니다 😊
