### ISSUE TITLE
[기능] 카카오맵 API 테스트

### ISSUE THREAD

**Issue by rohheejin** [BedalFriend/BaedalFriend-FE#5]
## 참고 사이트

-  [Kakao Developer](https://apis.map.kakao.com/web/sample/basicMarker/)

#### 배프모집 지도
- [x] 카카오맵 API 연결
- [x] 카카오맵 API 연결후 좌표 검색
- [x] 카카오맵 마커 추가
- [x] 카카오맵 반경 1km 설정
- [x] 원중심부터 마커까지 거리 계산
- [x] 반경 내에 있는 마커만 표시
- [x] 카카오맵 마커 이미지 변경
- [ ] isDone 타입에 대하여 마커 모집중/ 모집마감 구별
- [ ] 반경내 마커의 총개수

#### 건물 명 키워드 검색 지도
- [x] 카카오맵 API 연결
- [x] 키워드 검색에 대한 지도 정보표시
- [x] 검색후 확인할수있는 검색 리스트 생성

**Comment by JMKiim** [comment]
**건물 명 키워드 검색**으로 지도에 표시할 수 있는 기능이 필요합니다!
추가로 카카오 맵 마커 이미지 디자인은 디자이너님께 말씀드리면 될 것 같습니다.

**Comment by rohheejin** [comment]
@JMKiim 
추후에 앱 마커 이미지는 모집중과 모집마감에 따른 2가지 이미지를 디자이너분께 요청드릴려고합니다.
