### ISSUE TITLE
기본 레이아웃 마크업, CSS

### ISSUE THREAD

**Issue by JMKiim** [BedalFriend/BaedalFriend-FE#6]
## Description

> 서비스에서 공통적으로 사용자에게 보여질 공통적인 요소 마크업, CSS

## Progress

- [x] 상단 헤더, 사용자 주소 변경창, 채팅 버튼
- [x] 하단 gnb 플로팅 바, 
- [x] 홈 마이페이지 지도 업로드 버튼

**Comment by JMKiim** [comment]
디자이너님과 상의해본 결과
하단 gnb에는 (Home, Nearby, Upload, MyPage)
총 4개로 확정 됐습니다!

**Comment by mingki831** [comment]
넵 gnb 4가지 구성 좋네요!!
아 저희 기존에 상단바 아래에서부터 앱 화면이 떠서 헤더와 간격이 떨어졌던 문제는 어떻게 해결하셨나요??
아까 카톡에 이미지 보니까 해결된 것 같아서요!

**Comment by JMKiim** [comment]
> 넵 gnb 4가지 구성 좋네요!! 아 저희 기존에 상단바 아래에서부터 앱 화면이 떠서 헤더와 간격이 떨어졌던 문제는 어떻게 해결하셨나요?? 아까 카톡에 이미지 보니까 해결된 것 같아서요!

그 부분은 모바일 기종이 기본적으로 차지하는 상단 바 부분을 고려하지 못해서 생겼던 문제였습니다.
추가적으로 화면 오른쪽에 붙어있던 문제는 찾아보니 반응형 최대 너비를 400px로 지정해서 생겼던 문제였습니다.
